"""Publish the additive a104 V4 channel-taxonomy correction.

V3's empirical values and provenance receipts are retained.  Its comparison
language, however, can be misread as a direct prompt-articulability versus
code-verifiability experiment.  The three artifacts behind the historical
``prompt_compiled_baseline`` label are Python scorers generated by Claude:
their *authoring origin* is an LLM prompt, but their *runtime channel* is code.

V4 therefore describes the result as a within-code-channel comparison between
prompt-generated shallow executable programs, a pre-existing deeper static/AST
program, and a retrospective relation program.  Spearman rho remains agreement
with the frozen LLM-judgment reference.  It is not, by itself, an isomorphism
certificate; that term is reserved here for joint construct, input, program,
and reference fidelity.

This script performs no model/API/GPU calls and reads no external anchor.  Run
it once to create the three additive V4 artifacts, then use ``--check`` to
rebuild them in memory and require byte-for-byte equality.
"""
from __future__ import annotations

import argparse
import copy
import hashlib
import json
from pathlib import Path
from typing import Any


ROOT = Path(__file__).resolve().parents[3]
TASK = ROOT / "outputs/metric_seam_pilot/tasks/code_review"

V2_JSON = TASK / "a104_cpu_sealed_eval_v2.json"
V2_REPORT = TASK / "A104_CPU_SEALED_REPORT_V2.md"
V3_JSON = TASK / "a104_cpu_sealed_eval_v3.json"
V3_REPORT = TASK / "A104_CPU_SEALED_REPORT_V3.md"
V4_JSON = TASK / "a104_cpu_sealed_eval_v4.json"
V4_REPORT = TASK / "A104_CPU_SEALED_REPORT_V4.md"
V4_NOTICE = TASK / "A104_CPU_SEALED_REPORT_V4_CORRECTION_NOTICE.md"

# These bind the correction to the already-published historical artifacts.
EXPECTED_HISTORICAL_SHA256 = {
    V2_JSON: "fd6cd25b6c84663a58789fdf2e8ae2dcd334620a98ca16ea47586c9d2aca75bd",
    V2_REPORT: "5a53c07805cbc3ca115f779cc6dc7f1d53cf00c5516810ee610c4bfd4cf4567d",
    V3_JSON: "054b4f6252e94c7cbd1f8f451143be669989fa8a408e9788b8028d583d8d6eaa",
    V3_REPORT: "d8eda8a37e697af1206b85af8bd1124e191a8d55c432d956bfb6b12e0d373ebd",
}

BASELINE_KEYS = ("a104_v0_keyword", "a104_v1_structure", "a104_v2_holistic")
BASELINE_MECHANISMS = {
    "a104_v0_keyword": "Python regex keyword hits and bounded saturation",
    "a104_v1_structure": "Python regex counts, chunk coverage, and density saturation",
    "a104_v2_holistic": "Python regex signals, weighted blending, and tanh saturation",
}

PROVENANCE_KEYS_PRESERVED = (
    "comparison_inputs_verified_at_correction",
    "compute",
    "correction_input_receipt",
    "data_provenance",
    "execution_blindness",
    "freeze_verified_before_judge_load",
    "h0_authoring_certification",
    "h0_discovery_provenance",
    "h0_freeze_checks",
    "lane",
    "legacy_replay",
    "model_provenance",
    "objective",
)


def _sha(path: Path) -> str:
    return hashlib.sha256(path.read_bytes()).hexdigest()


def _display(path: Path) -> str:
    return path.relative_to(ROOT).as_posix()


def _verify_historical_artifacts() -> None:
    for path, expected in EXPECTED_HISTORICAL_SHA256.items():
        if not path.is_file():
            raise RuntimeError(f"missing frozen historical artifact: {_display(path)}")
        actual = _sha(path)
        if actual != expected:
            raise RuntimeError(
                f"historical artifact changed: {_display(path)} "
                f"(expected {expected}, found {actual})"
            )


def _verify_baseline_sources(v3: dict[str, Any]) -> dict[str, dict[str, str]]:
    sources = v3["comparison_inputs_verified_at_correction"]["sources"]
    if not set(BASELINE_KEYS).issubset(sources):
        raise RuntimeError("V3 is missing one or more prompt-generated baseline receipts")

    receipts: dict[str, dict[str, str]] = {}
    for key in BASELINE_KEYS:
        source = sources[key]
        path = ROOT / source["path"]
        if path.suffix != ".py" or not path.is_file():
            raise RuntimeError(f"baseline is not a readable Python source: {key}")
        actual = _sha(path)
        if actual != source["sha256"]:
            raise RuntimeError(f"baseline source no longer matches V3 receipt: {key}")
        text = path.read_text()
        if "def score(" not in text or "import re" not in text:
            raise RuntimeError(f"baseline lacks the expected executable regex scorer: {key}")
        if key == "a104_v2_holistic" and "tanh" not in text:
            raise RuntimeError("v2 holistic baseline lacks its recorded tanh mechanism")
        receipts[key] = {
            "artifact_role": "prompt_generated_shallow_executable_code",
            "runtime_channel": "code",
            "language": "Python",
            "path": source["path"],
            "sha256": actual,
            "mechanisms": BASELINE_MECHANISMS[key],
        }
    return receipts


def _numeric_leaves(value: Any, path: str = "") -> dict[str, int | float]:
    """Return non-boolean numeric leaves, keyed by their JSON-pointer-like path."""
    output: dict[str, int | float] = {}
    if isinstance(value, dict):
        for key, child in value.items():
            output.update(_numeric_leaves(child, f"{path}/{key}"))
    elif isinstance(value, list):
        for index, child in enumerate(value):
            output.update(_numeric_leaves(child, f"{path}/{index}"))
    elif isinstance(value, (int, float)) and not isinstance(value, bool):
        output[path] = value
    return output


def build_v4() -> dict[str, Any]:
    """Build and validate the V4 JSON payload without writing any artifact."""
    _verify_historical_artifacts()
    v3 = json.loads(V3_JSON.read_text())
    source_receipts = _verify_baseline_sources(v3)
    v4 = copy.deepcopy(v3)

    v4["schema_version"] = "metric-seam-active-code-review-a104-sealed-eval-v4"
    v4["supersedes"] = "a104_cpu_sealed_eval_v3.json"
    v4["supersession_scope"] = (
        "channel taxonomy and claim language only; V2/V3 remain byte-identical"
    )
    v4["prior_supersession_chain"] = [
        "a104_cpu_sealed_eval_v2.json",
        "a104_cpu_sealed_eval_v1.json",
    ]
    v4["correction_scope"] = (
        "runtime-channel taxonomy only; every numerical value and V3 provenance "
        "receipt is unchanged"
    )
    v4["claim_boundary"] = (
        "This is a within-code-channel reconstruction comparison. Spearman rho "
        "measures agreement with the frozen articulated LLM judgment; it does not "
        "compare direct prompt articulability with code verifiability, establish "
        "correctness on disagreements, or certify isomorphism by itself. Structural "
        "code evidence verifies test/source relations, not behavioural intent, oracle "
        "validity, or actual test success."
    )

    # The legacy JSON key is retained so every quantitative path stays stable.
    v4["baseline_selection"]["rule"] = (
        "highest Spearman on TRAIN among frozen prompt-generated shallow "
        "executable-code flavors"
    )
    v4["preexisting_deep_coded_checker"]["interpretation"] = (
        "the pre-existing deep executable-code verifier reconstructed the frozen LLM "
        "judgment better than the selected prompt-generated shallow executable-code "
        "baseline; this is a code-versus-code depth result, not code-over-prompt"
    )
    v4["retrospective_relation_h0"]["interpretation"] = (
        "positive but sub-gate retrospective manual/mock executable-code "
        "reconstruction; do not tune after held-out read"
    )

    v4["channel_taxonomy_v4"] = {
        "unit_of_classification": (
            "runtime evaluation program; authoring origin is recorded separately"
        ),
        "definitions": {
            "articulability": (
                "prompt-based implementation evaluated through prompt/model output"
            ),
            "verifiability": "code-based executable implementation",
            "reconstruction_agreement": (
                "agreement of a candidate program with the frozen LLM-judgment reference"
            ),
            "isomorphism": (
                "joint fidelity of construct, input representation, program channel, "
                "and reference instrument; rho alone is insufficient"
            ),
        },
        "historical_key_note": (
            "prompt_compiled_baseline is retained only as a stable legacy JSON key; "
            "it denotes prompt-generated Python code, not a direct prompt-output pole"
        ),
        "program_poles": {
            "prompt_generated_shallow_code": {
                "legacy_json_key": "prompt_compiled_baseline",
                "authoring_origin": "Claude-generated",
                "runtime_channel": "code",
                "implementation": "frozen Python text-to-score functions",
                "source_receipts": source_receipts,
            },
            "preexisting_deep_code": {
                "legacy_json_key": "preexisting_deep_coded_checker",
                "authoring_origin": "pre-existing manually engineered coding A-bank",
                "runtime_channel": "code",
                "implementation": "diff parsing plus static/AST test evidence",
            },
            "retrospective_relation_code": {
                "legacy_json_key": "retrospective_relation_h0",
                "authoring_origin": "manual/mock retrospective seed",
                "runtime_channel": "code",
                "implementation": "frozen Python relation program over CodeOps",
            },
            "reference": {
                "role": "frozen reconstruction target, not a compared program pole",
                "origin": "pre-existing two-pass model-produced LLM judgment",
            },
        },
        "comparison_type": "within_code_channel_program_depth_comparison",
        "direct_prompt_articulability_candidate_present": False,
        "code_verifiability_candidates_present": True,
        "permitted_conclusion": (
            "On the frozen common held-out support, the pre-existing deep code program "
            "has higher reconstruction agreement with the LLM judgment than the "
            "TRAIN-selected prompt-generated shallow code program; the retrospective "
            "relation code program is positive but below the registered gate."
        ),
        "not_permitted": [
            "direct prompt-articulability versus code-verifiability comparison",
            "code-over-prompt conclusion",
            "code correctness or superiority on reference disagreements",
            "isomorphism claim from correlation alone",
            "external-ground-truth claim",
        ],
    }
    v4["measurement_taxonomy_v4"] = {
        "reported_rho_quantity": "reconstruction_agreement_with_frozen_llm_judgment",
        "rho_is_channel_capability_measure": False,
        "rho_alone_certifies_isomorphism": False,
        "isomorphism_status": "not_certified_by_this_artifact",
        "isomorphism_required_fidelities": [
            "construct",
            "input_representation",
            "program_channel",
            "reference_instrument",
        ],
        "unsupervised_objective_unchanged": True,
        "external_anchor_used": False,
    }
    v4["channel_taxonomy_correction_receipt"] = {
        "v3_json": {"path": _display(V3_JSON), "sha256": _sha(V3_JSON)},
        "v3_report": {"path": _display(V3_REPORT), "sha256": _sha(V3_REPORT)},
        "historical_v2_v3_hashes_verified": True,
        "baseline_source_hashes_reverified": True,
        "model_api_or_gpu_used": False,
    }

    if _numeric_leaves(v4) != _numeric_leaves(v3):
        raise RuntimeError("V4 changed or added a numerical value; refusing publication")
    for key in PROVENANCE_KEYS_PRESERVED:
        if v4[key] != v3[key]:
            raise RuntimeError(f"V4 changed preserved V3 provenance field: {key}")
    return v4


def render_report(v4: dict[str, Any]) -> str:
    rhos = v4["heldout_rhos_common_intersection"]
    deep = v4["preexisting_deep_coded_checker"]
    h0 = v4["retrospective_relation_h0"]
    receipt = v4["channel_taxonomy_correction_receipt"]
    return f"""# Active coding census a104 — channel-taxonomy correction (V4)

## Corrected result

All empirical values and V3 provenance receipts are unchanged. On the common
held-out intersection (`n={v4['common_heldout_n']}`), the TRAIN-selected
prompt-generated shallow Python scorer (legacy JSON key
`prompt_compiled_baseline`) has Spearman rho
`{rhos['prompt_compiled_baseline']:.16f}` with the frozen LLM judgment. The
pre-existing deep static/AST code program has rho
`{rhos['preexisting_deep_coded_checker']:.16f}`
(delta `{deep['delta_vs_prompt_baseline']:+.16f}`, P(gate)
`{deep['P_gate']:.4f}`, P(beats) `{deep['P_beats_baseline']:.4f}`) and passes the
current pooled gate. The retrospective relation code program has rho
`{rhos['retrospective_relation_h0']:.16f}`
(delta `{h0['delta_vs_prompt_baseline']:+.16f}`, P(gate)
`{h0['P_gate']:.4f}`, P(beats) `{h0['P_beats_baseline']:.4f}`) and remains
sub-gate.

The warranted conclusion is narrower and cleaner: **the pre-existing deep
executable-code program reconstructs the frozen LLM judgment better than the
selected prompt-generated shallow executable-code program on this support.**
This is a within-code-channel program-depth comparison. It is not a direct
prompt-articulability versus code-verifiability comparison and is not a
code-over-prompt result.

## Why the channel label changed

All three historical “prompt-compiled” flavors are frozen Claude-generated
Python functions. Their mechanisms are regex keyword hits, regex
density/coverage, and regex plus weighted/tanh saturation. Prompt generation is
their authoring provenance; at evaluation time they are executable code. The
deep static/AST checker and retrospective `CodeOps` h0 are executable code too.
There is no direct prompt-output candidate pole in this a104 comparison.

The legacy key `prompt_compiled_baseline` remains in V4 so numerical paths and
downstream checks do not move. V4's `channel_taxonomy_v4` records its corrected
meaning explicitly.

## Four separate questions

- **Articulability** is prompt-based implementation. It is not measured as a
  candidate channel here.
- **Verifiability** is code-based executable implementation. The compared
  candidate programs all run in this channel, at different depths and with
  different authoring provenance.
- **Reconstruction agreement** is what the reported Spearman rho estimates:
  agreement with the frozen articulated LLM-judgment reference.
- **Isomorphism** is reserved for joint construct, input-representation,
  program-channel, and reference-instrument fidelity. Correlation alone does
  not certify it, so this artifact reports isomorphism as not certified.

No disagreement is adjudicated against external truth. Higher rho does not show
that code is correct where it differs from the LLM reference, and a lower rho
does not show tacitness.

## Provenance retained from V3

V3's manual/mock label-unreferenced—not label-inaccessible—classification for
the retrospective h0 is unchanged. Its corpus lineage, frozen input/program
hashes, comparison-source receipts, model-artifact disclosures, structural
coverage counts, and limitations are copied exactly into V4. No external
supervised anchor, model/API call, repository execution, or GPU was used for
this correction. The objective remains unsupervised reconstruction of the
articulated prompt judgment.

The correction is bound to V3 JSON SHA-256 `{receipt['v3_json']['sha256']}` and
V3 report SHA-256 `{receipt['v3_report']['sha256']}`.
"""


def render_notice(v4: dict[str, Any]) -> str:
    receipt = v4["channel_taxonomy_correction_receipt"]
    return f"""# Correction notice for a104 sealed CPU V4

`a104_cpu_sealed_eval_v2.json`, `a104_cpu_sealed_eval_v3.json`, and their
reports remain byte-identical historical artifacts. V4 supersedes only V3's
channel framing; every empirical value and provenance receipt is retained.

The artifacts historically called “prompt-compiled baselines” are frozen
Claude-generated Python regex/tanh scorers. Their authoring origin is an LLM
prompt, but their runtime evaluation channel is executable code. Consequently,
the a104 result compares deeper pre-existing verifier code with
prompt-generated shallow code (plus a retrospective relation-code h0). It does
**not** compare direct prompt articulability with code verifiability and must
not be quoted as code-over-prompt.

Spearman rho is labeled reconstruction agreement with the frozen LLM judgment.
“Isomorphism” is reserved for construct + input + program + reference fidelity
and is not certified by rho alone. The unsupervised reconstruction objective is
unchanged; no external anchor, model/API call, or GPU was used.

Frozen correction inputs:

- V3 JSON SHA-256: `{receipt['v3_json']['sha256']}`
- V3 report SHA-256: `{receipt['v3_report']['sha256']}`
"""


def expected_artifacts() -> dict[Path, bytes]:
    v4 = build_v4()
    return {
        V4_JSON: (json.dumps(v4, indent=2, sort_keys=True) + "\n").encode(),
        V4_REPORT: render_report(v4).encode(),
        V4_NOTICE: render_notice(v4).encode(),
    }


def _check(expected: dict[Path, bytes]) -> None:
    for path, wanted in expected.items():
        if not path.is_file():
            raise RuntimeError(f"missing V4 artifact: {_display(path)}")
        actual = path.read_bytes()
        if actual != wanted:
            raise RuntimeError(f"V4 artifact is not canonical: {_display(path)}")


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--check",
        action="store_true",
        help="rebuild in memory and require byte-identical existing V4 artifacts",
    )
    args = parser.parse_args()
    expected = expected_artifacts()
    if args.check:
        _check(expected)
        print("PASS: a104 V4 channel-taxonomy artifacts are canonical")
        return

    existing = [path for path in expected if path.exists()]
    if existing:
        names = ", ".join(_display(path) for path in existing)
        raise RuntimeError(f"refusing to overwrite existing V4 artifacts: {names}")
    for path, payload in expected.items():
        path.write_bytes(payload)
    for path in expected:
        print(f"{_sha(path)}  {_display(path)}")


if __name__ == "__main__":
    main()
