import copy
import json
from pathlib import Path

import pytest

from scripts.tools.silver_match_v3.common import sha256_file
from scripts.tools.silver_match_v3.freeze_cross_encoder_queue import (
    PRESS_RELEASES_POLICY_V2,
    _validate_policy_and_implementation,
)
from scripts.tools.silver_match_v3.freeze_press_releases_ce_policy_v3 import (
    ALLOWED_TOP_LEVEL_DIFFS,
    scientific_projection,
)


def test_semantic_projection_allows_only_rebind_metadata():
    v2 = {
        "schema_version": PRESS_RELEASES_POLICY_V2,
        "status": "old",
        "scope": ["press-releases"],
        "fixed_training": {"epochs": 2},
        "predeclared_variants": [{"name": "v"}],
        "implementation": {"train_cross_encoder_sha256": "missing"},
    }
    v3 = copy.deepcopy(v2)
    v3.update(
        {
            "status": "new",
            "policy_revision": "v3",
            "implementation": {"train_cross_encoder_sha256": "current"},
            "implementation_supersession": {"scientific_contract_changed": False},
        }
    )
    changed = {key for key in set(v2) | set(v3) if v2.get(key) != v3.get(key)}
    assert changed == ALLOWED_TOP_LEVEL_DIFFS
    assert scientific_projection(v2) == scientific_projection(v3)


def test_freezer_accepts_exact_pr_scope_and_binds_both_implementations(tmp_path):
    repo = tmp_path / "repo"
    tools = repo / "scripts" / "tools" / "silver_match_v3"
    tools.mkdir(parents=True)
    trainer = tools / "train_cross_encoder.py"
    selector = tools / "select_cross_encoder_variants.py"
    trainer.write_text("trainer\n", encoding="utf-8")
    selector.write_text("selector\n", encoding="utf-8")
    policy = {
        "schema_version": PRESS_RELEASES_POLICY_V2,
        "policy_revision": "v3",
        "scope": ["press-releases"],
        "implementation": {
            "train_cross_encoder_path": "scripts/tools/silver_match_v3/train_cross_encoder.py",
            "train_cross_encoder_sha256": sha256_file(trainer),
            "select_cross_encoder_variants_path": "scripts/tools/silver_match_v3/select_cross_encoder_variants.py",
            "select_cross_encoder_variants_sha256": sha256_file(selector),
        },
    }
    audit = _validate_policy_and_implementation(policy, "press-releases", repo)
    assert audit["policy_binding_verified"] is True
    assert set(audit["artifacts"]) == {
        "train_cross_encoder",
        "select_cross_encoder_variants",
    }

    stale = copy.deepcopy(policy)
    stale["implementation"]["train_cross_encoder_sha256"] = "0" * 64
    with pytest.raises(ValueError, match="hash mismatch"):
        _validate_policy_and_implementation(stale, "press-releases", repo)
    with pytest.raises(ValueError, match="unsupported"):
        _validate_policy_and_implementation(policy, "peer-review", repo)
    widened = copy.deepcopy(policy)
    widened["scope"].append("peer-review")
    with pytest.raises(ValueError, match="unsupported"):
        _validate_policy_and_implementation(widened, "press-releases", repo)


def test_checked_in_v3_policy_has_equal_scientific_projection():
    root = Path(__file__).resolve().parents[4]
    policies = root / "scripts" / "tools" / "silver_match_v3" / "policies"
    v2_path = policies / "press_releases_cross_encoder_policy_v2.json"
    v3_path = policies / "press_releases_cross_encoder_policy_v3.json"
    if not v3_path.exists():
        pytest.skip("v3 policy is generated by the append-only freeze step")
    v2 = json.loads(v2_path.read_text(encoding="utf-8"))
    v3 = json.loads(v3_path.read_text(encoding="utf-8"))
    assert v3["schema_version"] == v2["schema_version"]
    assert scientific_projection(v3) == scientific_projection(v2)
