from __future__ import annotations

from methods.metric_seam.science_claims_v2 import core_relation_strict as strict


def test_metric_identity_not_shared_method_name_controls_percentage() -> None:
    result = strict.verify_document(
        "iclr_RVPZJpmyGU",
        "Through evaluations, we show that VQMoE achieves a 28% improvement in "
        "robustness compared to other SMoE routing methods.",
        "Allowing VQMoE to save 28% of computational resources compared to SMoE.",
    )
    assert result["status"] != "supported"
    assert not result["certificates"]


def test_large_count_requires_local_entity_not_shared_conclusion() -> None:
    result = strict.verify_document(
        "iclr_IA3wm5vwUl",
        "Experimental results with up to 1000 nodes demonstrate that the solutions "
        "generated by the DEDD model are nearly optimal.",
        "After 1000 rounds of DR iteration, the DEDD model nearly achieves optimal "
        "performance.",
    )
    assert result["status"] != "supported"


def test_quantity_obligations_cannot_reuse_one_nearby_evidence_value() -> None:
    result = strict.verify_document(
        "iclr_PIpGN5Ko3v",
        "The relative decrease reaches 90.9% in one setting and 91.3% in another.",
        "The relative performance drop reaches 91.3% in the evaluated setting.",
    )
    assert result["status"] != "supported"


def test_quantity_matching_is_bijective_positive_control() -> None:
    result = strict.verify_document(
        "two-values",
        "The accuracy gains reach 90.9% in setting A and 91.3% in setting B.",
        "Table 2 reports accuracy gains of 90.9% in setting A and 91.3% in setting B.",
    )
    assert result["status"] == "supported"
    assert result["certificates"][0]["checks"]["quantity_matches"] == 2


def test_codec_version_is_not_a_numeric_relation() -> None:
    assert strict.extract_quantities("JPEG and AVC/H.264 codecs") == ()
    result = strict.verify_document(
        "iclr_Z7aq3djHZw",
        "We propose to model images and videos as JPEG and AVC/H.264 files.",
        "The AVC/H.264 codec is modeled by an autoregressive transformer.",
    )
    assert result["status"] != "supported"
    assert not result["certificates"]


def test_function_math_norm_and_calendar_identifiers_are_not_quantities() -> None:
    for text in (
        "Shifted-Cosh, Linex(1/2), and Linex(1)",
        "a (1+O(alpha))-approximation",
        r"perturbation models $\ell_{2}$ and $\ell_{\infty}$",
        "the ℓ2 and ℓ∞ threat models",
        "since August 30, 2024",
        "as of Aug 30, 2024",
    ):
        assert strict.extract_quantities(text) == (), text


def test_real_parenthesized_count_and_decimal_measurement_remain() -> None:
    quantities = strict.extract_quantities("We evaluate tasks (12 public datasets).")
    assert len(quantities) == 1
    assert quantities[0].value == 12
    quantities = strict.extract_quantities("The score is 0.264.")
    assert len(quantities) == 1
    assert quantities[0].value == 0.264


def test_interrogative_or_hypothetical_comparison_is_not_support() -> None:
    claim = "Our analysis shows that OTDF outperforms prior strong baselines."
    for evidence in (
        "Can OTDF beat prior strong baselines across varied shifts?",
        "OTDF could outperform prior strong baselines under a future assumption.",
    ):
        result = strict.verify_document("iclr_LRrbD8EZJl", claim, evidence)
        assert result["status"] != "supported"


def test_assertive_comparison_checks_baseline_direction_and_roles() -> None:
    claim = "We show that our method outperforms BERT."
    supported = strict.verify_document(
        "support", claim, "Table 2 shows that our method outperforms BERT."
    )
    baseline = strict.verify_document(
        "baseline", claim, "Table 2 shows that our method outperforms RoBERTa."
    )
    reversed_roles = strict.verify_document(
        "roles", claim, "Table 2 shows that BERT outperforms our method."
    )
    assert supported["status"] == "supported"
    assert baseline["status"] != "supported"
    assert reversed_roles["status"] == "contradicted"


def test_normalized_units_must_agree() -> None:
    result = strict.verify_document(
        "units",
        "We report latency of 5 seconds on the benchmark.",
        "Table 2 reports latency of 5 milliseconds on the benchmark.",
    )
    assert result["status"] != "supported"


def test_stronger_weaker_is_an_executable_role_reversal() -> None:
    result = strict.verify_document(
        "elo",
        "Our agent is 400 Elo stronger than behavioral cloning.",
        "Behavioral cloning is 400 Elo weaker than our agent.",
    )
    assert result["status"] == "supported"
    certificate = result["certificates"][0]
    assert certificate["claim"]["relation"] == "comparative"
    assert certificate["checks"]["relation_state"] == "aligned_reversed"


def test_metamorphic_relation_suite() -> None:
    checks = strict.metamorphic_self_check()
    assert len(checks) == 10
    assert all(checks.values())
