"""Manual categorization of all 368 creative_writing aspects.

Categories:
  RELAX     — broadly assessable on most fiction; currently marked N/A too often.
  STRICT    — genuinely narrow domain (format/process/genre-specific).
  BORDERLINE — close call, worth flagging.

Decisions were made by reading every aspect's name+description. Rationale codes:
  GENRE   — specific to a genre (romance, noir, cozy mystery, satire, etc.)
  FORMAT  — specific to a format (poetry, comics, screenplay, picture book, etc.)
  STRUCT  — only applies to specific story structures (unreliable narrator, epistolary, subplot, ensemble)
  PROCESS — publishing-process or submission norms (query, synopsis, market-fit, comps)
  SPEC    — speculative fiction specific (magic system, worldbuilding rules, etc.)
  HIST    — historical fiction specific
  FORML   — format-craft outside fiction (essay/argument/criticism/informative)
  NARROW_BUT_BROAD — the underlying principle is universal but the rubric's name pins it to a narrow genre
"""

CATEGORIZATION = {
    # ---- a0-a48: Aristotelian + foundational fiction craft ----
    "a0": ("RELAX", "Every story has plot vs spectacle balance"),
    "a1": ("RELAX", "Every story has plot"),
    "a2": ("STRICT", "FORMAT - verse/drama-specific"),
    "a3": ("RELAX", "Reframe as emotional payoff — every story has one"),
    "a4": ("BORDERLINE", "Could be re-read as 'scope discipline'; tragedy framing"),
    "a5": ("STRICT", "FORMAT - genre-form-specific"),
    "a6": ("RELAX", "Every story has key scenes"),
    "a7": ("RELAX", "Universal"),
    "a8": ("RELAX", "Most stories use some plot devices"),
    "a9": ("RELAX", "Universal"),
    "a10": ("RELAX", "Universal show/tell"),
    "a11": ("RELAX", "Universal"),
    "a12": ("RELAX", "Most prose can be assessed"),
    "a13": ("RELAX", "Universal"),
    "a14": ("RELAX", "Universal"),
    "a15": ("RELAX", "Universal"),
    "a16": ("RELAX", "Most stories have a turn"),
    "a17": ("RELAX", "Universal"),
    "a18": ("RELAX", "Universal"),
    "a19": ("RELAX", "Every story has POV"),
    "a20": ("RELAX", "Universal"),
    "a21": ("RELAX", "Universal"),
    "a22": ("BORDERLINE", "'Sublime' is a specific aesthetic mode"),
    "a23": ("RELAX", "Universal — any style choice can be assessed for restraint"),
    "a24": ("BORDERLINE", "More prominent in some prose"),
    "a25": ("RELAX", "Universal"),
    "a26": ("STRICT", "SPEC - speculative-only"),
    "a27": ("STRICT", "SPEC"),
    "a28": ("BORDERLINE", "STRUCT - only stories with subplots/ensemble"),
    "a29": ("RELAX", "Universal"),
    "a30": ("RELAX", "Universal"),
    "a31": ("RELAX", "Universal"),
    "a32": ("RELAX", "Universal"),
    "a33": ("RELAX", "Universal prose criterion"),
    "a34": ("RELAX", "Universal"),
    "a35": ("RELAX", "Universal"),
    "a36": ("STRICT", "STRUCT - frame narrative-specific"),
    "a37": ("RELAX", "Universal"),
    "a38": ("STRICT", "GENRE - tragedy-specific"),
    "a39": ("STRICT", "GENRE - tragedy-specific"),
    "a40": ("RELAX", "Universal"),
    "a41": ("RELAX", "Universal"),
    "a42": ("RELAX", "Universal"),
    "a43": ("RELAX", "Universal scene craft"),
    "a44": ("RELAX", "Universal"),
    "a45": ("RELAX", "Universal"),
    "a46": ("RELAX", "Universal"),
    "a47": ("RELAX", "Universal — every promise/payoff cycle"),
    "a48": ("RELAX", "Universal"),
    # ---- a49-a99: Plot/prose/character/POV/setting craft ----
    "a49": ("RELAX", "Universal"),
    "a50": ("RELAX", "Universal"),
    "a51": ("RELAX", "Universal"),
    "a52": ("RELAX", "Universal"),
    "a53": ("RELAX", "Universal"),
    "a54": ("RELAX", "Universal"),
    "a55": ("RELAX", "Universal"),
    "a56": ("RELAX", "Universal"),
    "a57": ("RELAX", "Universal"),
    "a58": ("RELAX", "Universal"),
    "a59": ("STRICT", "STRUCT - only unreliable-narrator stories"),
    "a60": ("STRICT", "STRUCT - experimental works"),
    "a61": ("STRICT", "STRUCT - nonlinear works only"),
    "a62": ("RELAX", "Universal"),
    "a63": ("RELAX", "Universal"),
    "a64": ("RELAX", "Universal"),
    "a65": ("RELAX", "Universal"),
    "a66": ("RELAX", "Universal — every story has some dialogue or considers it"),
    "a67": ("STRICT", "STRUCT - subplot-only"),
    "a68": ("STRICT", "STRUCT - subplot"),
    "a69": ("STRICT", "SPEC/GENRE"),
    "a70": ("STRICT", "SPEC - magic system"),
    "a71": ("RELAX", "Universal"),
    "a72": ("RELAX", "Universal"),
    "a73": ("RELAX", "Universal"),
    "a74": ("STRICT", "GENRE - autobio/historical-specific"),
    "a75": ("RELAX", "Universal"),
    "a76": ("STRICT", "FORMAT - visual/multimedia"),
    "a77": ("STRICT", "GENRE - thriller-specific"),
    "a78": ("RELAX", "Every story has a genre"),
    "a79": ("RELAX", "Universal"),
    "a80": ("RELAX", "Universal"),
    "a81": ("STRICT", "STRUCT - ensemble"),
    "a82": ("RELAX", "Universal — and explicitly engagement-flavored"),
    "a83": ("RELAX", "Universal"),
    "a84": ("RELAX", "Universal"),
    "a85": ("RELAX", "Universal"),
    "a86": ("RELAX", "Universal"),
    "a87": ("RELAX", "Universal"),
    "a88": ("RELAX", "Universal"),
    "a89": ("RELAX", "Universal"),
    "a90": ("RELAX", "Universal"),
    "a91": ("RELAX", "Universal"),
    "a92": ("STRICT", "SPEC"),
    "a93": ("STRICT", "SPEC"),
    "a94": ("RELAX", "Universal"),
    "a95": ("STRICT", "GENRE - mythic/folkloric"),
    "a96": ("RELAX", "Universal"),
    "a97": ("RELAX", "Universal"),
    "a98": ("RELAX", "Universal"),
    "a99": ("RELAX", "Universal"),
    # ---- a100-a148: Subplot/genre/scene/character craft ----
    "a100": ("STRICT", "STRUCT - subplot"),
    "a101": ("RELAX", "Universal"),
    "a102": ("RELAX", "Universal"),
    "a103": ("RELAX", "Universal"),
    "a104": ("RELAX", "Universal"),
    "a105": ("BORDERLINE", "Poetic/prosaic split"),
    "a106": ("STRICT", "GENRE - comedic/satirical"),
    "a107": ("STRICT", "GENRE - historical fiction"),
    "a108": ("STRICT", "FORMAT - comics"),
    "a109": ("RELAX", "Universal"),
    "a110": ("RELAX", "Universal"),
    "a111": ("RELAX", "Universal"),
    "a112": ("RELAX", "Universal — every story has genre signals"),
    "a113": ("BORDERLINE", "Sanskrit aesthetics — niche but interpretable as 'aesthetic suggestion'"),
    "a114": ("RELAX", "Universal"),
    "a115": ("STRICT", "STRUCT - experimental"),
    "a116": ("RELAX", "Universal"),
    "a117": ("RELAX", "Universal"),
    "a118": ("RELAX", "Universal"),
    "a119": ("STRICT", "SPEC - magic/puzzle systems"),
    "a120": ("RELAX", "Universal"),
    "a121": ("RELAX", "Universal"),
    "a122": ("RELAX", "Universal"),
    "a123": ("RELAX", "Universal"),
    "a124": ("RELAX", "Universal"),
    "a125": ("RELAX", "Universal"),
    "a126": ("RELAX", "Universal"),
    "a127": ("RELAX", "Universal"),
    "a128": ("RELAX", "Universal — Chekhov's economy"),
    "a129": ("RELAX", "Universal — KEY engagement norm"),
    "a130": ("RELAX", "Universal — KEY ending payoff"),
    "a131": ("RELAX", "Universal"),
    "a132": ("RELAX", "Universal"),
    "a133": ("RELAX", "Universal — KEY narrative drive"),
    "a134": ("RELAX", "Universal"),
    "a135": ("RELAX", "Universal"),
    "a136": ("RELAX", "Universal"),
    "a137": ("RELAX", "Universal"),
    "a138": ("RELAX", "Universal"),
    "a139": ("RELAX", "Universal"),
    "a140": ("RELAX", "Universal"),
    "a141": ("RELAX", "Universal"),
    "a142": ("RELAX", "Universal"),
    "a143": ("RELAX", "Universal — even mundane stories have a 'world'"),
    "a144": ("RELAX", "Universal"),
    "a145": ("RELAX", "Universal"),
    "a146": ("RELAX", "Universal"),
    "a147": ("RELAX", "Universal"),
    "a148": ("RELAX", "Universal"),
    # ---- a149-a248: Representation/setting/POV/plot/genre ----
    "a149": ("RELAX", "Universal"),
    "a150": ("STRICT", "FORMAT - visual"),
    "a151": ("BORDERLINE", "FORMAT-adjacent"),
    "a152": ("STRICT", "STRUCT - subplot/timeline-specific"),
    "a153": ("STRICT", "GENRE - humor-specific"),
    "a154": ("RELAX", "Universal"),
    "a155": ("RELAX", "Universal"),
    "a156": ("RELAX", "Universal"),
    "a157": ("RELAX", "Universal"),
    "a158": ("RELAX", "Universal"),
    "a159": ("STRICT", "SPEC"),
    "a160": ("STRICT", "SPEC"),
    "a161": ("STRICT", "SPEC"),
    "a162": ("RELAX", "Universal"),
    "a163": ("RELAX", "Universal"),
    "a164": ("RELAX", "Universal"),
    "a165": ("RELAX", "Universal"),
    "a166": ("RELAX", "Universal"),
    "a167": ("RELAX", "Universal"),
    "a168": ("STRICT", "STRUCT - unreliable narration"),
    "a169": ("RELAX", "Universal"),
    "a170": ("RELAX", "Universal"),
    "a171": ("RELAX", "Universal"),
    "a172": ("RELAX", "Universal"),
    "a173": ("STRICT", "FORMAT - poetry"),
    "a174": ("STRICT", "FORMAT - visual"),
    "a175": ("RELAX", "Universal — medium-fit applies broadly"),
    "a176": ("STRICT", "GENRE - satire"),
    "a177": ("RELAX", "Universal"),
    "a178": ("RELAX", "Universal"),
    "a179": ("RELAX", "Universal"),
    "a180": ("RELAX", "Universal"),
    "a181": ("RELAX", "Universal"),
    "a182": ("STRICT", "FORMAT - flash/short-form-specific"),
    "a183": ("RELAX", "Universal"),
    "a184": ("RELAX", "Universal — KEY affective impact"),
    "a185": ("RELAX", "Universal"),
    "a186": ("RELAX", "Universal"),
    "a187": ("RELAX", "Universal"),
    "a188": ("RELAX", "Universal"),
    "a189": ("RELAX", "Universal"),
    "a190": ("RELAX", "Universal — KEY opening hook"),
    "a191": ("RELAX", "Universal"),
    "a192": ("RELAX", "Universal"),
    "a193": ("RELAX", "Universal"),
    "a194": ("RELAX", "Universal"),
    "a195": ("RELAX", "Universal"),
    "a196": ("RELAX", "Universal"),
    "a197": ("STRICT", "SPEC - worldbuilding-heavy"),
    "a198": ("STRICT", "SPEC"),
    "a199": ("RELAX", "Universal"),
    "a200": ("RELAX", "Universal — genre awareness is universal"),
    "a201": ("STRICT", "GENRE - noir"),
    "a202": ("RELAX", "Universal"),
    "a203": ("STRICT", "STRUCT - ensemble"),
    "a204": ("RELAX", "Universal"),
    "a205": ("RELAX", "Universal"),
    "a206": ("RELAX", "Universal"),
    "a207": ("RELAX", "Universal"),
    "a208": ("STRICT", "FORMAT - visual"),
    "a209": ("STRICT", "GENRE - historical"),
    "a210": ("STRICT", "GENRE - satire"),
    "a211": ("RELAX", "Universal — form/content alignment is universal"),
    "a212": ("STRICT", "STRUCT - epistolary"),
    "a213": ("STRICT", "PROCESS - query/synopsis"),
    "a214": ("RELAX", "Universal"),
    "a215": ("RELAX", "Universal"),
    "a216": ("RELAX", "Universal"),
    "a217": ("STRICT", "FORMAT - poetry"),
    "a218": ("RELAX", "Universal"),
    "a219": ("RELAX", "Universal"),
    "a220": ("STRICT", "FORMAT - short-story-specific"),
    "a221": ("STRICT", "SPEC - worldbuilding-heavy"),
    "a222": ("STRICT", "SPEC"),
    "a223": ("RELAX", "Universal"),
    "a224": ("RELAX", "Universal"),
    "a225": ("RELAX", "Universal"),
    "a226": ("RELAX", "Universal"),
    "a227": ("RELAX", "Universal — KEY opening"),
    "a228": ("RELAX", "Universal — KEY ending"),
    "a229": ("RELAX", "Universal"),
    "a230": ("RELAX", "Universal"),
    "a231": ("RELAX", "Universal"),
    "a232": ("STRICT", "GENRE - romance"),
    "a233": ("RELAX", "Universal — KEY emotional engagement"),
    "a234": ("BORDERLINE", "Sanskrit rasa concept"),
    "a235": ("RELAX", "Universal"),
    "a236": ("STRICT", "FORMAT - comics"),
    "a237": ("STRICT", "FORMAT - screenwriting"),
    "a238": ("RELAX", "Universal"),
    "a239": ("RELAX", "Universal — KEY reader immersion"),
    "a240": ("RELAX", "Universal"),
    "a241": ("RELAX", "Universal"),
    "a242": ("RELAX", "Universal"),
    "a243": ("STRICT", "PROCESS - query/pitch"),
    "a244": ("STRICT", "PROCESS - synopsis"),
    "a245": ("RELAX", "Universal"),
    "a246": ("RELAX", "Universal"),
    "a247": ("RELAX", "Universal"),
    "a248": ("STRICT", "SPEC - worldbuilding"),
    # ---- a249-a367: Worldbuilding/POV/process/publishing/format ----
    "a249": ("STRICT", "SPEC"),
    "a250": ("RELAX", "Universal"),
    "a251": ("RELAX", "Universal"),
    "a252": ("RELAX", "Universal"),
    "a253": ("RELAX", "Universal"),
    "a254": ("RELAX", "Universal — KEY page-one hook"),
    "a255": ("RELAX", "Universal"),
    "a256": ("RELAX", "Universal"),
    "a257": ("RELAX", "Universal"),
    "a258": ("RELAX", "Universal — KEY reader momentum"),
    "a259": ("RELAX", "Universal"),
    "a260": ("RELAX", "Universal"),
    "a261": ("RELAX", "Universal"),
    "a262": ("RELAX", "Universal"),
    "a263": ("STRICT", "GENRE - historical"),
    "a264": ("RELAX", "Universal"),
    "a265": ("RELAX", "Universal"),
    "a266": ("RELAX", "Universal"),
    "a267": ("STRICT", "FORMAT - interactive narrative/games"),
    "a268": ("STRICT", "FORMAT - picture book"),
    "a269": ("STRICT", "FORMAT - cross-media adaptation"),
    "a270": ("STRICT", "FORMAT - flash/short"),
    "a271": ("RELAX", "Universal"),
    "a272": ("RELAX", "Universal"),
    "a273": ("RELAX", "Universal"),
    "a274": ("RELAX", "Universal"),
    "a275": ("RELAX", "Universal"),
    "a276": ("RELAX", "Universal"),
    "a277": ("RELAX", "Universal"),
    "a278": ("RELAX", "Universal — KEY opening hook"),
    "a279": ("RELAX", "Universal"),
    "a280": ("RELAX", "Universal"),
    "a281": ("RELAX", "Universal"),
    "a282": ("RELAX", "Universal"),
    "a283": ("STRICT", "GENRE - research-driven"),
    "a284": ("RELAX", "Universal"),
    "a285": ("STRICT", "SPEC - worldbuilding-heavy"),
    "a286": ("RELAX", "Universal"),
    "a287": ("STRICT", "STRUCT - experimental/hybrid"),
    "a288": ("RELAX", "Universal — every story has a title"),
    "a289": ("STRICT", "PROCESS - query/pitch"),
    "a290": ("STRICT", "GENRE - cozy mystery"),
    "a291": ("STRICT", "GENRE - romance"),
    "a292": ("RELAX", "Universal"),
    "a293": ("STRICT", "FORML - argumentative essay"),
    "a294": ("STRICT", "PROCESS - publishing design"),
    "a295": ("RELAX", "Universal"),
    "a296": ("RELAX", "Universal"),
    "a297": ("RELAX", "Universal"),
    "a298": ("RELAX", "Universal"),
    "a299": ("STRICT", "PROCESS - market fit"),
    "a300": ("STRICT", "FORMAT - comics"),
    "a301": ("RELAX", "Universal"),
    "a302": ("RELAX", "Universal"),
    "a303": ("RELAX", "Universal — KEY reader engagement"),
    "a304": ("STRICT", "GENRE - memoir"),
    "a305": ("STRICT", "FORML - criticism/essay"),
    "a306": ("RELAX", "Universal"),
    "a307": ("RELAX", "Universal — KEY opening hook"),
    "a308": ("RELAX", "Universal"),
    "a309": ("RELAX", "Universal"),
    "a310": ("RELAX", "Universal — KEY narrative voice"),
    "a311": ("STRICT", "PROCESS - query"),
    "a312": ("STRICT", "PROCESS - publishing"),
    "a313": ("STRICT", "PROCESS - venue submission"),
    "a314": ("RELAX", "Universal"),
    "a315": ("RELAX", "Universal"),
    "a316": ("RELAX", "Universal"),
    "a317": ("RELAX", "Universal"),
    "a318": ("RELAX", "Universal"),
    "a319": ("RELAX", "Universal"),
    "a320": ("STRICT", "FORMAT - translation"),
    "a321": ("STRICT", "FORML - argumentative essay"),
    "a322": ("RELAX", "Universal — task fulfillment is broad"),
    "a323": ("RELAX", "Universal"),
    "a324": ("RELAX", "Universal"),
    "a325": ("STRICT", "PROCESS - publishing metadata"),
    "a326": ("STRICT", "PROCESS - AO3 platform-specific"),
    "a327": ("STRICT", "GENRE - afterlife stories"),
    "a328": ("STRICT", "STRUCT - epistolary"),
    "a329": ("STRICT", "GENRE - youth/MG/YA"),
    "a330": ("STRICT", "STRUCT - unreliable narration"),
    "a331": ("RELAX", "Universal"),
    "a332": ("STRICT", "GENRE - research-driven (historical)"),
    "a333": ("STRICT", "PROCESS - publishing layout"),
    "a334": ("RELAX", "Universal"),
    "a335": ("RELAX", "Universal"),
    "a336": ("RELAX", "Universal"),
    "a337": ("STRICT", "FORML - informative prose"),
    "a338": ("STRICT", "FORMAT - cross-media"),
    "a339": ("STRICT", "FORMAT - games"),
    "a340": ("RELAX", "Universal"),
    "a341": ("RELAX", "Universal"),
    "a342": ("RELAX", "Universal"),
    "a343": ("RELAX", "Universal"),
    "a344": ("STRICT", "FORMAT - audio"),
    "a345": ("RELAX", "Universal — KEY voice"),
    "a346": ("RELAX", "Universal"),
    "a347": ("RELAX", "Universal"),
    "a348": ("RELAX", "Universal"),
    "a349": ("STRICT", "PROCESS - venue submission"),
    "a350": ("STRICT", "PROCESS - query"),
    "a351": ("STRICT", "PROCESS - query"),
    "a352": ("STRICT", "PROCESS - query"),
    "a353": ("STRICT", "PROCESS - comps"),
    "a354": ("STRICT", "PROCESS - querying"),
    "a355": ("STRICT", "PROCESS - submission"),
    "a356": ("STRICT", "PROCESS - publisher fit"),
    "a357": ("RELAX", "Universal — originality of one's own work"),
    "a358": ("STRICT", "PROCESS - submission rule"),
    "a359": ("STRICT", "PROCESS - submission rule"),
    "a360": ("STRICT", "GENRE - research-driven"),
    "a361": ("RELAX", "Universal"),
    "a362": ("RELAX", "Universal"),
    "a363": ("STRICT", "PROCESS - publishing"),
    "a364": ("STRICT", "FORMAT - cross-medium"),
    "a365": ("STRICT", "GENRE - fanfic"),
    "a366": ("STRICT", "PROCESS - publishing"),
    "a367": ("STRICT", "PROCESS - submission credentials"),
}


def main():
    from collections import Counter
    cats = Counter(v[0] for v in CATEGORIZATION.values())
    print("=== Categorization summary ===")
    for c, n in sorted(cats.items(), key=lambda x: -x[1]):
        print(f"  {c:<10} {n}")
    print(f"  total       {sum(cats.values())}")
    # Output IDs per category for use in re-scoring pipeline
    import json
    out = {
        "RELAX": [a for a, (c, _) in CATEGORIZATION.items() if c == "RELAX"],
        "STRICT": [a for a, (c, _) in CATEGORIZATION.items() if c == "STRICT"],
        "BORDERLINE": [a for a, (c, _) in CATEGORIZATION.items() if c == "BORDERLINE"],
    }
    p = "/lfs/skampere3/0/alexspan/norm-research/outputs/v2_analysis/cw_aspect_categorization.json"
    with open(p, "w") as f:
        json.dump(out, f, indent=2)
    print(f"\nwrote {p}")


if __name__ == "__main__":
    main()
