#!/usr/bin/env python3
"""Legacy circular cross-executor diagnostic (not an executor fidelity gate).

The frozen source behavior was generated by the incumbent 8B executor, so agreement
with it cannot select between 8B and 70B.  New executor selection must use
``experiments.ceiling_ladder`` and its independent Sonnet/planted references.
"""
from __future__ import annotations

import argparse
import hashlib
import json
import os
from pathlib import Path
from typing import Mapping, Sequence

import numpy as np
import pandas as pd

from methods.metric_implementer.batch_scoring import _YESNO_TEMPLATE
from methods.metric_implementer.config import ImplementerConfig, apply_task_preset
from methods.metric_implementer.experiments.run_v13_value_campaign import (
    _load_codebook_for_entry,
    load_metrics_manifest,
)
from methods.metric_implementer.experiments.v14_value_bound import (
    balanced_agreement,
    binary_entropy_bits,
    plugin_binary_mutual_information,
)
from methods.metric_implementer.vllm_backend import (
    CR3_BINARY_READOUT_ID,
    make_judge_backend,
    model_revision_id,
)


DEFAULT_KEYS = tuple(f"humor_R3_metric{value}" for value in (0, 10, 11, 12, 34, 50))
READOUT_ID = CR3_BINARY_READOUT_ID


def _file_sha256(path: str | Path) -> str:
    digest = hashlib.sha256()
    with Path(path).open("rb") as handle:
        for block in iter(lambda: handle.read(1 << 20), b""):
            digest.update(block)
    return digest.hexdigest()


def _atomic_json(path: Path, payload: Mapping[str, object]) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    temporary = path.with_name(f".{path.name}.tmp-{os.getpid()}")
    temporary.write_text(json.dumps(payload, indent=2, allow_nan=False), encoding="utf-8")
    os.replace(temporary, path)


def _atomic_npz(path: Path, **arrays: object) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    temporary = path.with_name(f".{path.name}.tmp-{os.getpid()}.npz")
    np.savez_compressed(temporary, **arrays)
    os.replace(temporary, path)


def _probe_sha256(probes: Sequence[str]) -> str:
    packed = json.dumps(list(probes), ensure_ascii=False, separators=(",", ":"))
    return hashlib.sha256(packed.encode("utf-8")).hexdigest()


def _cache_namespace(
    task: str, probes: Sequence[str], model: str, revision: str, max_chars: int,
) -> tuple[str, dict]:
    payload = {
        "task": str(task), "probe_sha256": _probe_sha256(probes),
        "executor_model": str(model), "executor_model_revision": str(revision),
        "readout_id": READOUT_ID,
        "yesno_template_sha256": hashlib.sha256(_YESNO_TEMPLATE.encode("utf-8")).hexdigest(),
        "max_text_chars": int(max_chars),
    }
    packed = json.dumps(payload, sort_keys=True, separators=(",", ":"))
    return hashlib.sha256(packed.encode("utf-8")).hexdigest(), payload


def _score_seed(namespace: str, criterion: str, index: int) -> int:
    packed = f"{READOUT_ID}\x1f{namespace}\x1f{criterion}\x1f{index}"
    return int.from_bytes(hashlib.sha256(packed.encode()).digest()[:8], "big") & ((1 << 63) - 1)


def _checked_signature(
    executor, criterion: str, probes: Sequence[str], max_chars: int, namespace: str,
) -> np.ndarray:
    prompts = [
        _YESNO_TEMPLATE.format(rubric=criterion, text=str(text)[:max_chars])
        for text in probes
    ]
    seeds = [_score_seed(namespace, criterion, index) for index in range(len(probes))]
    scores = np.asarray(executor.score_binary_constrained(
        prompts, pos="YES", neg="NO", seed=seeds,
    ), dtype=float)
    if scores.shape != (len(probes),) or np.any(~np.isfinite(scores)):
        raise RuntimeError("executor returned an invalid signature")
    return scores


def _rewritten(path: str | Path) -> Path:
    value = str(path)
    rewrites = json.loads(os.environ.get("V13_PATH_REWRITE_JSON", "{}"))
    for source, destination in sorted(rewrites.items(), key=lambda item: -len(item[0])):
        if value == source or value.startswith(source.rstrip("/") + "/"):
            value = destination.rstrip("/") + value[len(source.rstrip("/")):]
            break
    return Path(value)


def _source_checkpoint(
    bootstrap: Mapping[str, object], entry: Mapping[str, object], base: Path,
) -> Path:
    expected = str(bootstrap["source_checkpoint_sha256"])
    raw_candidates = [
        str(bootstrap["source_checkpoint"]),
        str(entry.get("candidate_bank_path") or ""),
    ]
    candidates = []
    for raw in raw_candidates:
        if not raw:
            continue
        path = Path(raw)
        if not path.is_absolute():
            path = base / path
        candidates.extend([path, _rewritten(path)])
    for path in candidates:
        if path.is_file() and _file_sha256(path) == expected:
            return path.resolve()
    raise FileNotFoundError(
        f"no source checkpoint matches {expected[:12]}...; searched {list(map(str, candidates))}"
    )


def _binary_auc(target: Sequence[int], scores: Sequence[float]) -> float | None:
    labels = np.asarray(target, dtype=np.uint8)
    values = np.asarray(scores, dtype=float)
    positive = values[labels == 1]
    negative = values[labels == 0]
    if not len(positive) or not len(negative):
        return None
    comparisons = positive[:, None] - negative[None, :]
    return float(np.mean(comparisons > 0) + 0.5 * np.mean(comparisons == 0))


def _kappa(left: Sequence[int], right: Sequence[int]) -> float | None:
    a = np.asarray(left, dtype=np.uint8)
    b = np.asarray(right, dtype=np.uint8)
    observed = float(np.mean(a == b))
    expected = float(np.mean(a) * np.mean(b) + np.mean(1 - a) * np.mean(1 - b))
    if expected == 1.0:
        return None
    return float((observed - expected) / (1.0 - expected))


def _fidelity(reference: np.ndarray, scores: np.ndarray) -> dict:
    truth = (np.asarray(reference, dtype=float) > 0.5).astype(np.uint8)
    prediction = (np.asarray(scores, dtype=float) > 0.5).astype(np.uint8)
    return {
        "auc": _binary_auc(truth, scores),
        "accuracy": float(np.mean(truth == prediction)),
        "balanced_agreement": balanced_agreement(truth, prediction),
        "mutual_information_bits": plugin_binary_mutual_information(truth, prediction),
        "cohen_kappa": _kappa(truth, prediction),
        "reference_positive_rate": float(np.mean(truth)),
        "predicted_positive_rate": float(np.mean(prediction)),
        "reference_entropy_bits": binary_entropy_bits(truth),
    }


def _cross_executor(old_scores: np.ndarray, new_scores: np.ndarray) -> dict:
    old = (np.asarray(old_scores) > 0.5).astype(np.uint8)
    new = (np.asarray(new_scores) > 0.5).astype(np.uint8)
    return {
        "binary_agreement": float(np.mean(old == new)),
        "balanced_agreement_old_as_reference": balanced_agreement(old, new),
        "mutual_information_bits": plugin_binary_mutual_information(old, new),
        "cohen_kappa": _kappa(old, new),
        "old_positive_rate": float(np.mean(old)),
        "new_positive_rate": float(np.mean(new)),
    }


def _cache_signature(
    *, executor, criterion: str, probes: list[str], max_chars: int,
    namespace: str, cache_root: Path,
) -> np.ndarray:
    criterion_sha = hashlib.sha256(criterion.encode("utf-8")).hexdigest()
    path = cache_root / namespace / f"{criterion_sha}.npz"
    if path.is_file():
        with np.load(path, allow_pickle=False) as artifact:
            if str(artifact["criterion"]) != criterion:
                raise RuntimeError("criterion cache collision")
            result = np.asarray(artifact["signature"], dtype=float)
        if result.shape != (len(probes),) or np.any(~np.isfinite(result)):
            raise RuntimeError(f"invalid cached signature in {path}")
        return result
    result = _checked_signature(executor, criterion, probes, max_chars, namespace)
    _atomic_npz(
        path, signature=result, criterion=np.asarray(criterion),
        criterion_sha256=np.asarray(criterion_sha), namespace_sha256=np.asarray(namespace),
    )
    return result


def run(args: argparse.Namespace) -> dict:
    if not bool(getattr(args, "allow_circular_cross_executor_diagnostic", False)):
        raise RuntimeError(
            "refusing the circular frozen_8b_bootstrap fidelity gate; use the independent "
            "ceiling_ladder reference phase. Pass --allow-circular-cross-executor-diagnostic "
            "only to reproduce the historical executor-disagreement diagnostic."
        )
    out = Path(args.out_root).resolve()
    manifest, base = load_metrics_manifest(args.metrics_manifest)
    requested = tuple(args.metric_keys)
    entries = {str(row["metric_key"]): dict(row) for row in manifest["metrics"]}
    if set(requested) != set(DEFAULT_KEYS) or not set(requested).issubset(entries):
        raise ValueError("the executor gate requires exactly the six frozen humor sentinels")

    cfg = ImplementerConfig()
    apply_task_preset(cfg, "humor")
    cfg.vllm_gpu_mem_util = float(os.environ.get("VLLM_GPU_MEM_UTIL", "0.90"))
    cfg.vllm_tp_size = 1
    cfg.vllm_max_model_len = int(os.environ.get("VLLM_MAX_MODEL_LEN", "8192"))
    if os.environ.get("METRIC_IMPLEMENTER_LFS_HOME"):
        cfg.vllm_lfs_home = os.environ["METRIC_IMPLEMENTER_LFS_HOME"]
    revision = model_revision_id(args.executor_path)
    executor = make_judge_backend(args.executor_path, cfg, 0.0)

    rows = []
    for metric_key in requested:
        entry = entries[metric_key]
        codebook = _load_codebook_for_entry(entry, base)
        bootstrap_path = Path(codebook["metrics"][metric_key]["bootstrap_path"])
        with np.load(bootstrap_path, allow_pickle=True) as frozen:
            bootstrap = {name: frozen[name] for name in frozen.files}
        probes = [str(value) for value in bootstrap["probe_texts"]]
        forms = [str(value) for value in bootstrap["target_form_texts"]]
        if len(probes) != 300 or not forms:
            raise RuntimeError(f"invalid frozen bootstrap for {metric_key}")
        source_path = _source_checkpoint(bootstrap, entry, base)
        with np.load(source_path, allow_pickle=True) as source:
            if "M_i" not in source.files:
                raise RuntimeError(f"source checkpoint lacks M_i: {source_path}")
            operational = np.asarray(source["M_i"], dtype=float)
        old_target = np.asarray(bootstrap["target"], dtype=float)
        if operational.shape != (300,) or old_target.shape != (300,):
            raise RuntimeError(f"unaligned source behavior for {metric_key}")

        max_chars = int(cfg.max_text_chars)
        namespace, namespace_payload = _cache_namespace(
            "humor", probes, args.executor_model, revision, max_chars,
        )
        form_signatures = np.vstack([
            _cache_signature(
                executor=executor, criterion=form, probes=probes, max_chars=max_chars,
                namespace=namespace, cache_root=out / "signature_cache",
            )
            for form in forms
        ])
        new_target = np.mean(form_signatures, axis=0)
        per_form = [_fidelity(operational, signature) for signature in form_signatures]
        result = {
            "metric_key": metric_key,
            "n_probes": 300,
            "n_frozen_description_forms": len(forms),
            "source_checkpoint": str(source_path),
            "source_checkpoint_sha256": _file_sha256(source_path),
            "frozen_8b_bootstrap": str(bootstrap_path),
            "frozen_8b_bootstrap_sha256": _file_sha256(bootstrap_path),
            "executor_8b_model": str(bootstrap["executor_model"]),
            "executor_8b_revision": str(bootstrap["executor_model_revision"]),
            "executor_70b_model": args.executor_model,
            "executor_70b_revision": revision,
            "readout_id": READOUT_ID,
            "cache_namespace": namespace_payload,
            "fidelity_8b": _fidelity(operational, old_target),
            "fidelity_70b": _fidelity(operational, new_target),
            "fidelity_70b_by_form": per_form,
            "cross_executor": _cross_executor(old_target, new_target),
        }
        result["delta_70b_minus_8b"] = {
            key: (
                None if result["fidelity_8b"][key] is None or result["fidelity_70b"][key] is None
                else float(result["fidelity_70b"][key] - result["fidelity_8b"][key])
            )
            for key in ("auc", "accuracy", "balanced_agreement", "mutual_information_bits", "cohen_kappa")
        }
        metric_out = out / "metrics" / metric_key
        _atomic_npz(
            metric_out / "executor_signatures.npz",
            operational_source=operational, frozen_8b_target=old_target,
            rescored_70b_target=new_target, rescored_70b_forms=form_signatures,
            target_form_texts=np.asarray(forms, dtype=object),
        )
        _atomic_json(metric_out / "fidelity.json", result)
        rows.append(result)
        print(
            f"[{metric_key}] BA {result['fidelity_8b']['balanced_agreement']:.4f} -> "
            f"{result['fidelity_70b']['balanced_agreement']:.4f}; "
            f"AUC {result['fidelity_8b']['auc']:.4f} -> {result['fidelity_70b']['auc']:.4f}",
            flush=True,
        )

    frame_rows = []
    for row in rows:
        flat = {"metric_key": row["metric_key"]}
        for executor_name in ("8b", "70b"):
            for key, value in row[f"fidelity_{executor_name}"].items():
                flat[f"{executor_name}_{key}"] = value
        for key, value in row["delta_70b_minus_8b"].items():
            flat[f"delta_{key}"] = value
        frame_rows.append(flat)
    frame = pd.DataFrame(frame_rows)
    parquet_path = out / "results.parquet"
    temporary = parquet_path.with_name(f".{parquet_path.name}.tmp-{os.getpid()}")
    frame.to_parquet(temporary, index=False)
    os.replace(temporary, parquet_path)
    summary = {
        "schema": "cr3-cross-executor-disagreement-diagnostic-v2",
        "scope": "six frozen humor sentinels; no v14 scientific phase",
        "metric_keys": list(requested),
        "executor_candidate": args.executor_model,
        "executor_candidate_revision": revision,
        "comparison": (
            "gold-description orbit signatures under each executor versus the identical frozen "
            "source operational behavior M_i on 300 probes"
        ),
        "valid_for_executor_selection": False,
        "circularity": (
            "the reference operational behavior was generated by the incumbent 8B executor; "
            "8B agreement is therefore privileged by construction"
        ),
        "valid_finding": "cross-executor disagreement on the same frozen criteria",
        "rows": rows,
        "aggregate": {
            "mean_balanced_agreement_8b": float(frame["8b_balanced_agreement"].mean()),
            "mean_balanced_agreement_70b": float(frame["70b_balanced_agreement"].mean()),
            "mean_delta_balanced_agreement": float(frame["delta_balanced_agreement"].mean()),
            "mean_auc_8b": float(frame["8b_auc"].mean()),
            "mean_auc_70b": float(frame["70b_auc"].mean()),
            "mean_delta_auc": float(frame["delta_auc"].mean()),
            "n_balanced_agreement_improved": int(np.sum(frame["delta_balanced_agreement"] > 0)),
            "n_auc_improved": int(np.sum(frame["delta_auc"] > 0)),
            "n_70b_balanced_agreement_at_least_0_75": int(
                np.sum(frame["70b_balanced_agreement"] >= 0.75)
            ),
        },
        "results_parquet": str(parquet_path),
    }
    _atomic_json(out / "gate_report.json", summary)
    print(json.dumps(summary["aggregate"], sort_keys=True), flush=True)
    return summary


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--metrics-manifest", required=True)
    parser.add_argument("--out-root", required=True)
    parser.add_argument("--executor-model", default="meta-llama/Llama-3.3-70B-Instruct")
    parser.add_argument("--executor-path", required=True)
    parser.add_argument("--metric-keys", nargs="+", default=list(DEFAULT_KEYS))
    parser.add_argument("--allow-circular-cross-executor-diagnostic", action="store_true")
    run(parser.parse_args())
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
