def score(text: str) -> float:
    try:
        if not text or not text.strip():
            return 0.5
        t = text.lower()
        tl = len(t)
        if tl < 30:
            return 0.3

        import re
        import math

        severity_terms = {
            "physical assault": 4.5, "grabbed": 3.5, "punched": 3.5, "slapped": 3.5,
            "shoved": 3.5, "struck": 3.0, "physically attacked": 4.0,
            "raped": 4.5, "sexual assault": 4.5, "groped": 3.5, "sexually assaulted": 4.5,
            "death threat": 4.0, "threatened to kill": 4.0, "threatened with a": 3.0,
            "threatened to shoot": 4.0, "threat of violence": 3.5, "threatened to rape": 4.0,
            "noose": 3.5, "weapon": 2.5, "gun": 2.5, "knife": 2.5, "strangled": 4.0,
            "choked": 3.5, "choking": 3.0, "burned": 2.5, "burned a cross": 4.0,
            "vandalized": 2.0, "damaged her car": 2.0, "damaged his car": 2.0,
            "slashed her tires": 2.5, "slashed his tires": 2.5,
            "chewed tobacco": 2.0, "spit on": 3.0, "spat on": 3.0,
            "inappropriate touching": 3.0, "touched her": 2.5, "touched his": 2.5,
            "unwanted touching": 3.0, "grabbed her": 3.0, "grabbed his": 3.0,
            "put his hand": 2.0, "put her hand": 2.0,
            "exposed himself": 3.5, "exposed herself": 3.5,
            "exposed his": 3.0, "exposed her": 3.0,
            "forced her": 3.0, "forced him": 3.0,
            "requested sexual": 2.5, "demanded sexual": 3.0, "quid pro quo": 3.0,
            "breasts": 2.5, "buttocks": 2.5, "genitals": 2.5, "crotch": 2.0,
            "humped": 3.0, "bumped": 1.5, "rubbed": 2.5, "massaged": 2.0,
            "brushed against": 1.5, "stood so close": 1.5, "cornered": 2.5,
            "pinched": 2.5, "kissed": 2.5, "hugged": 2.0, "made a pass": 2.0,
            "tried to kiss": 2.5, "stared at her": 1.5, "leered": 1.5,
            "made sexual advances": 2.5, "made unwanted": 2.5, "made lewd": 2.5,
            "sexual comments": 2.0, "lewd comments": 2.0, "vulgar comments": 2.0,
            "obscene comments": 2.0, "derogatory comments": 2.0,
            "sexual propositions": 2.5, "propositioned": 2.5,
            "n-word": 3.5, "n word": 2.5, "racial slur": 3.0, "racist slur": 3.0,
            "racial slurs": 3.0, "racist remarks": 2.5, "racial epithet": 3.0,
            "racial epithets": 3.0, "racist jokes": 2.0, "racist graffiti": 2.5,
            "monkey": 2.5, "spic": 3.0, "wetback": 3.0, "chink": 3.0,
            "gook": 3.0, "kike": 3.0, "wetbacks": 2.5, "monkeys": 2.0,
            "porch monkey": 3.0, "raghead": 3.0, "towel head": 2.5,
            "ragheads": 2.5, "jungle bunny": 2.5, "sambo": 2.5,
            "spade": 2.0, "spook": 2.5, "coon": 2.5, "jig": 2.0, "jigaboo": 3.0,
            "heeb": 2.5, "sheenie": 2.5, "kikes": 2.5, "fag": 2.5, "faggot": 3.0,
            "dyke": 2.5, "tranny": 2.5, "queer": 1.5, "bitch": 2.0,
            "cunt": 2.0, "whore": 2.0, "slut": 2.0, "ho": 1.0, "the b word": 1.5,
            "dog": 0.3, "ugly": 1.0, "stupid": 0.5, "fat": 0.5, "idiot": 0.3,
            "bimbo": 1.5, "honey": 0.5, "sweetheart": 0.5, "sweetie": 0.5,
            "bitched": 1.0, "asshole": 1.0, "jackass": 0.8, "dumbass": 0.8,
            "shut up": 0.5,
            "indecent exposure": 2.5, "rape": 3.5, "molest": 3.0, "molested": 3.5,
            "molestation": 3.0, "pedophile": 3.0, "assaulted": 2.5, "battery": 2.5,
            "battered": 2.5, "struck her": 2.5, "struck him": 2.5, "hit her": 2.5,
            "hit him": 2.5, "pushed her": 2.0, "pushed him": 2.0,
            "followed her": 2.0, "followed him": 2.0, "stalked": 2.5,
            "surveilled": 1.5, "spied on": 1.5, "watched her": 1.0,
            "watched him": 1.0, "restroom": 1.5, "bathroom": 1.5,
            "blocked her": 2.0, "blocked him": 2.0, "blocked the door": 2.0,
            "trapped": 2.5, "wouldn't let her leave": 2.5, "would not let her leave": 2.5,
            "locked the door": 2.0, "locked her": 2.5, "locked him": 2.5,
            "grabbed her arm": 3.0, "grabbed his arm": 3.0, "grabbed her breast": 3.5,
            "grinding": 2.5, "humping": 2.5, "thrusting": 2.5,
            "cum": 2.5, "sperm": 2.0, "semen": 2.0,
            "stripped": 2.5, "undressed": 2.0, "unzipped": 2.0, "unbuttoned": 1.5,
            "pulled out his": 2.5, "pulled out her": 2.5,
            "touched himself": 2.5, "touched herself": 2.5,
            "masturbated": 3.0, "masturbating": 3.0, "fondled": 3.0,
            "kissing": 2.0, "rubbing": 2.0, "moaning": 1.5,
            "moans": 1.0, "groans": 0.5, "grunts": 0.5,
            "spread rumors": 0.5, "rumors about": 0.5, "rumours about": 0.5,
            "hostile work environment": 0.3, "hostile environment": 0.3,
            "harassing": 0.3, "harassed": 0.3, "harassment": 0.3,
            "discriminated": 0.3, "discrimination": 0.3, "prejudice": 0.3,
            "intimidated": 1.0, "intimidating": 1.0, "intimidation": 1.0,
            "retaliated": 0.5, "retaliation": 0.5,
            "screamed": 1.0, "yelled": 1.0, "shouted": 1.0, "belittled": 1.0,
            "humiliated": 1.5, "embarrassed": 0.5, "degraded": 1.5,
            "dehumanizing": 1.5, "degrading": 1.5, "degradation": 1.5,
            "ostracized": 1.0, "ignored": 0.3, "excluded": 0.5,
            "isolated": 0.5, "sabotaged": 1.5, "undermined": 0.8,
            "mocked": 1.0, "made fun of": 0.8, "ridiculed": 1.0,
            "teased": 0.5, "taunted": 1.5, "insulted": 1.0,
            "insults": 0.8, "insulting": 0.8, "derogatory": 0.8,
            "disparaging": 0.8, "pejorative": 0.8, "offensive": 0.3,
            "unwelcome": 0.5, "unwanted": 0.5, "uninvited": 0.5,
            "inappropriate": 0.3, "inappropriate conduct": 0.5,
            "demeaning": 1.0, "contempt": 0.5, "scorn": 0.5,
            "threatening": 1.5, "threats": 1.0, "threatened": 1.5,
            "abusive": 0.8, "abuse": 0.8, "abused": 0.8,
            "taunt": 1.0, "slur": 1.5, "slurs": 1.5, "epithet": 1.5,
            "epithets": 1.5, "name-calling": 0.8, "name calling": 0.8,
            "offensive language": 0.8, "profanity": 0.5,
            "profane": 0.5, "swore": 0.5, "swearing": 0.5,
            "cursed": 0.5, "cursing": 0.5, "vulgar": 0.5, "crude": 0.5,
            "lewd": 1.5, "obscene": 1.5, "indecent": 1.5,
            "pornographic": 2.0, "pornography": 1.5, "porn": 1.5,
            "centerfold": 1.5, "pin-up": 1.0, "pinup": 1.0,
            "nude pictures": 1.5, "nude photos": 1.5,
            "naked pictures": 1.5, "naked photos": 1.5,
            "explicit images": 1.5, "obscene materials": 1.5,
            "obscene material": 1.5, "dirty jokes": 0.8, "dirty joke": 0.8,
            "sexual jokes": 0.8, "sexual joke": 0.8, "sexist jokes": 0.8,
            "sexist joke": 0.8, "offensive jokes": 0.5, "offensive joke": 0.5,
            "suggestive": 1.0, "innuendo": 1.0, "double entendres": 1.0,
            "double entendre": 1.0, "double-entendre": 1.0,
            "catcalls": 1.5, "catcall": 1.5, "wolf whistles": 1.0,
            "ogled": 1.5, "ogling": 1.5, "staring": 1.0,
            "unwelcome touching": 3.0, "unwelcome sexual": 2.0,
            "sexual favors": 1.5, "sexual advances": 1.5,
            "quid pro quo": 3.0, "sleep with me": 3.0, "sleep with him": 2.0,
            "have sex": 1.5, "have intercourse": 1.5,
            "sexual intercourse": 1.5, "oral sex": 2.0,
            "anal sex": 2.0, "intercourse": 1.0,
            "dates": 0.3, "go out with me": 0.8, "go out with him": 0.5,
            "asked her out": 0.8, "asked him out": 0.8,
            "breast": 2.0, "butt": 1.5, "legs": 1.0, "cleavage": 1.5,
            "anatomy": 0.8, "body parts": 0.8,
            "commented on her": 1.0, "commented on his": 0.8,
            "commented on": 0.5, "remarks about": 0.5,
            "stared at": 1.0, "looked her up and down": 1.5,
            "mentally disabled": 1.5, "retard": 2.5, "retarded": 2.0,
            "crippled": 2.0, "wheelchair": 1.0, "mobility": 0.3,
            "disability": 0.3, "disabled": 0.3, "impairment": 0.3,
            "pregnant": 0.8, "pregnancy": 0.5, "maternity": 0.3,
            "religious garb": 1.0, "head scarf": 1.0, "hijab": 1.0,
            "yarmulke": 1.0, "turban": 1.0, "religion": 0.3,
            "religious": 0.3, "atheist": 0.5, "muslim": 0.5, "jew": 0.5,
            "jewish": 0.3, "christian": 0.3, "catholic": 0.3,
            "older workers": 0.5, "too old": 1.5, "over the hill": 1.5,
            "grandma": 1.5, "grandpa": 1.5, "old fart": 1.5,
            "age": 0.3, "older": 0.1, "younger": 0.1,
            "accent": 0.8, "national origin": 0.3, "immigrant": 0.8,
            "alien": 0.5, "foreigner": 0.5, "english": 0.2,
            "carved": 1.0, "spray-painted": 1.5, "spray painted": 1.5,
            "defaced": 1.5, "scrawled": 1.0, "painted": 0.3,
            "written on": 0.5, "written on the wall": 1.0,
            "wrote": 0.3, "distributed": 0.8, "circulated": 0.8,
            "posted": 0.5, "displayed": 0.5, "showed": 0.5,
            "emailed": 0.8, "texted": 0.8, "text message": 0.8,
            "email": 0.5, "letter": 0.5, "note": 0.5, "memo": 0.5,
            "cartoon": 1.0, "drawing": 1.0, "picture": 0.5,
            "photograph": 0.5, "image": 0.3, "video": 0.8,
            "recording": 0.5, "recorded